# Dependabot will run on day 2 of each month at 03:06 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "6 3 2 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "6 3 2 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "6 3 2 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
